### ISSUE TITLE
无法获取邮件授权码

### ISSUE THREAD

**Issue by yizhiduozai** [qhy040404/DLUT-library-auto-reservation#110]
点击前往网页版邮箱后，没有反应。生成计划任务是指第二天早上6.30开始抢座位吗

**Comment by qhy040404** [comment]
是6点半，图书馆系统6点半开始预约

**Comment by yizhiduozai** [comment]
需要运行程序吗？还是添加计划就可以完成

**Comment by qhy040404** [comment]
计划任务就是运行6点半自动运行

**Comment by yizhiduozai** [comment]
授权码是指SMTP吗还是其他的，那个链接还是无法自动跳转

**Comment by qhy040404** [comment]
> 授权码是指SMTP吗还是其他的，那个链接还是无法自动跳转

是smtp

**Comment by yizhiduozai** [comment]
很抱歉还是要麻烦您，下载压缩包后在configGenerator完成了配置，点击文件夹中的main程序后，发送了邮件，这样就算是配置成功了吗？第二天就可以自动运行了吗，还是需要自己点击main程序运行

**Comment by qhy040404** [comment]
如果你设了计划任务就会自动运行了，发邮件了算是配置成功了

**Comment by yizhiduozai** [comment]
您好，早上六点半好像并没有自动运行和发邮件，只有我自己点击压缩包中的main函数才会发邮件提醒失败，这是什么原因呢

**Comment by qhy040404** [comment]
他是在本地运行，不是云预约的
